# Generated by Django 4.2.27 on 2026-02-11 22:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_product_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('complete_when', models.CharField(choices=[('amount', 'Solo por monto'), ('stock', 'Solo por stock (sin stock)'), ('either', 'Monto o sin stock')], db_index=True, default='amount', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('achieved', 'Cumplido (monto)'), ('exhausted', 'Finalizado (sin stock)'), ('canceled', 'Cancelado')], db_index=True, default='active', max_length=10)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_stock', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='goals.goal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_items', to='products.product')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='goalproduct',
            constraint=models.UniqueConstraint(fields=('goal', 'product'), name='uniq_goal_product'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['owner', 'status'], name='goals_goal_owner_i_0c3e30_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['status', 'complete_when'], name='goals_goal_status_b9b8e2_idx'),
        ),
    ]
