# Generated by Django 4.2.27 on 2026-02-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='goals/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='photo_b64',
            field=models.TextField(blank=True, verbose_name='Foto (Base64)'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='photo_mime',
            field=models.CharField(blank=True, max_length=50, verbose_name='Foto MIME'),
        ),
    ]
