# Generated by Django 4.2.27 on 2026-02-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_photo_alter_goal_photo_b64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalproduct',
            name='goal_stock_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
