# Generated by Django 4.2.27 on 2026-02-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goalproduct_goal_stock_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='motivo',
            field=models.TextField(blank=True, help_text='Describe por qué se necesita alcanzar este objetivo', verbose_name='Motivo / Descripción'),
        ),
    ]
