# Generated by Django 4.2.27 on 2026-02-13 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goalproduct_goal_stock_sold'),
        ('cart', '0002_order_orderitem_orderitem_order_item_qty_gt_0_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uniq_cart_product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='goals.goal'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'goal'), name='uniq_cart_product_goal'),
        ),
    ]
