# Generated by Django 4.2.27 on 2026-01-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_b64',
            field=models.TextField(blank=True, verbose_name='Foto (Base64)'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_mime',
            field=models.CharField(blank=True, max_length=50, verbose_name='Foto MIME'),
        ),
    ]
